// This file is auto-generated by the CI/CD pipeline.
// The BUILD_NUMBER is injected by the GitHub Actions workflow at build time.
// When running locally, it defaults to 'dev'.
export const APP_VERSION = '2.4.0';
export const BUILD_NUMBER = 'dev';
